logo: "https://github.com/mnpaa/mnpaa.github.com/blob/master/logo.png?raw=true"  
  <br><br>
  <a href="https://stackoverflow.com/users/4539838/amit-kumar">View My Stackoverflow Profile</a> 
  
darkmode: true

theme: jekyll-theme-minimal
