title: Amit Kumar
logo: "https://github.com/mnpaa/mnpaa.github.io/blob/master/logo.png?raw=true" 
description: >
  Java - Full Stack Developer , 
  Hyderbad - Telangana 
  <br><br>
  <a href="https://www.linkedin.com/in/mnpaa/">View My LinkedIn Profile</a> 
  <br><br>
   
theme: jekyll-theme-minimal
