title: Amit Kumar
logo: "https://github.com/mnpaa/mnpaa.github.com/blob/master/logo.png?raw=true" 
description: >
  Java - Full Stack Developer , 
  Hyderbad - Telangana 
  <br><br>
  <a href="https://www.linkedin.com/in/mnpaa/">View My LinkedIn Profile</a> 
  <br><br>
  [Stackoverflow Profile](https://stackoverflow.com/users/4539838/amit-kumar)

  
email: mnpaa1991@gmail.com   

additional_links:
- title: Twitter
  url: <a href="https://twitter.com/BawlaPandit?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @BawlaPandit</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  
darkmode: true

theme: jekyll-theme-minimal
